### ISSUE TITLE
New Feature Request: Connect two newly created shapes

### ISSUE THREAD

**Issue by harshithaa-h** [dave-howard/vsdx#10]
I am trying to connect 2 shape objects , but I did not find any way to connect two shapes with a dynamic connector object.
Can you please introduce this feature soon.

**Comment by dave-howard** [comment]
Hello - been a while since you raised this - but there is now a Connect object with a create method which will create a new connection between two existing shapes.
`page = vis.pages[0]  # type: VisioFile.Page`
`from_shape = page.find_shape_by_text(shape_a_text)`
`to_shape = page.find_shape_by_text(shape_b_text)`
`c = VisioFile.Connect.create(page=page, from_shape=from_shape, to_shape=to_shape)`
`vis.save_vsdx(your_out_file_path)`
This creates the new connector shape, and relationships, masters etc. behind the scenes.

Refer to test `test_add_connect_between_shapes()` for an example

**Note**: it does not place the connector in the right place as yet, but if you move one the shapes in Visio it will update the locations.

**Comment by z3ndrag0n** [comment]
when I try and use VisioFile.connect.create I get a file not found error on ...\\site-packages\\media\\media.vsdx tracing back to __init.py__ line 1509 `media=Media()` - do you want a separate issue raised for this?

**Comment by dave-howard** [comment]
Hello @z3ndrag0n  - thanks for raising, no need for separate issue. I'll look into this.

**Comment by dave-howard** [comment]
Hello again - v0.4.14 pushed which has that missing media file included in the package. I was able to recreate your issue, and upgrade resolved for me so hopefully will for you also.
Kind regards
Dave

**Comment by dave-howard** [comment]
Hi @z3ndrag0n  - v0.4.19 should improve the positioning of connector shapes.  Please have a go with new version and let me know either way. Not a simple change - hence the delay - but I hope it works for you,
Dave
